# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 14:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enjoy_orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('desc', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'verbose_name': '\u5546\u54c1',
                'verbose_name_plural': '\u5546\u54c1',
            },
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': '\u8ba2\u5355', 'verbose_name_plural': '\u8ba2\u5355'},
        ),
        migrations.AddField(
            model_name='orders',
            name='good',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='enjoy_orders.Goods'),
            preserve_default=False,
        ),
    ]
