# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enjoy_orders', '0003_auto_20170822_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='pay_id',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='\u652f\u4ed8id'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.SmallIntegerField(default=0, verbose_name='\u72b6\u6001'),
        ),
    ]
