# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 03:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='\u5e7f\u544a\u6761\u76ee')),
                ('url', models.URLField(verbose_name='\u8df3\u8f6c\u5730\u5740')),
                ('valid', models.BooleanField(default=True, verbose_name='\u662f\u5426\u6709\u6548')),
                ('expire_time', models.DateTimeField(null=True, verbose_name='\u8fc7\u671f\u65f6\u95f4')),
                ('show_place', models.SmallIntegerField(choices=[(0, '\u6240\u6709\u4f4d\u7f6e'), (1, '\u4eba\u7269\u5217\u8868\u9875'), (2, '\u6587\u7ae0\u5217\u8868\u9875')], verbose_name='\u5c55\u793a\u7684tab')),
                ('show_page', models.IntegerField(default=1, verbose_name='\u5c55\u793a\u7684\u9875\u6570')),
                ('show_position', models.IntegerField(default=10, verbose_name='\u5c55\u793a\u7684\u4f4d\u7f6e')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '\u5e7f\u544a\u8bbe\u7f6e',
                'verbose_name_plural': '\u5e7f\u544a\u8bbe\u7f6e',
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_url', models.URLField(verbose_name='\u56fe\u7247\u5730\u5740')),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5220\u9664')),
                ('delete_time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', related_query_name='albums', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20, verbose_name='\u8054\u7cfb\u65b9\u5f0f\u7c7b\u578b')),
                ('content', models.CharField(max_length=20, verbose_name='\u8054\u7cfb\u65b9\u5f0f\u5185\u5bb9')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact', related_query_name='contact', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20, verbose_name='\u540d\u79f0')),
                ('value', models.CharField(max_length=100, verbose_name='\u503c')),
                ('valid', models.BooleanField(default=True, verbose_name='\u662f\u5426\u6709\u6548')),
            ],
            options={
                'verbose_name': 'app\u8bbe\u7f6e',
                'verbose_name_plural': 'app\u8bbe\u7f6e',
            },
        ),
        migrations.CreateModel(
            name='IdentityVerify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_name', models.CharField(max_length=20, verbose_name='\u771f\u5b9e\u59d3\u540d')),
                ('id_number', models.CharField(max_length=20, verbose_name='\u8eab\u4efd\u8bc1\u53f7')),
                ('img_front', models.URLField(verbose_name='\u6b63\u9762\u8eab\u4efd\u8bc1')),
                ('img_back', models.URLField(verbose_name='\u80cc\u9762\u8eab\u4efd\u8bc1')),
                ('status', models.SmallIntegerField(choices=[(0, '\u5f85\u5ba1\u6838'), (1, '\u5df2\u540c\u610f'), (2, '\u5df2\u62d2\u7edd')], default=0, verbose_name='\u5ba1\u6838\u72b6\u6001')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity', related_query_name='identity', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '\u8eab\u4efd\u8ba4\u8bc1',
                'verbose_name_plural': '\u8eab\u4efd\u8ba4\u8bc1',
            },
        ),
        migrations.CreateModel(
            name='PersonalInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u5174\u8da3\u7231\u597d')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u4e2a\u4eba\u6807\u7b7e')),
                ('valid', models.BooleanField(default=True, verbose_name='\u662f\u5426\u6709\u6548')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '\u4e2a\u4eba\u6807\u7b7e',
                'verbose_name_plural': '\u4e2a\u4eba\u6807\u7b7e',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=15, unique=True, verbose_name='\u7528\u6237\u540d')),
                ('sex', models.SmallIntegerField(choices=[(0, '\u4e0d\u8be6'), (1, '\u7537'), (2, '\u5973')], default=0, verbose_name='\u6027\u522b')),
                ('person_intro', models.TextField(blank=True, max_length=1000, null=True, verbose_name='\u4e2a\u4eba\u7b80\u4ecb')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='\u51fa\u751f\u65e5\u671f')),
                ('work_area_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u5de5\u4f5c\u5730\u540d\u79f0')),
                ('work_area_code', models.CharField(blank=True, max_length=15, null=True, verbose_name='\u5de5\u4f5c\u5730\u7f16\u7801')),
                ('born_area_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u7c4d\u8d2f\u540d\u79f0')),
                ('born_area_code', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u7c4d\u8d2f\u7f16\u7801')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='\u8eab\u9ad8')),
                ('education', models.SmallIntegerField(choices=[(0, '\u672a\u900f\u9732'), (1, '\u5c0f\u5b66'), (2, '\u4e2d\u5b66'), (3, '\u5927\u5b66'), (4, '\u7855\u58eb\u7814\u7a76\u751f'), (4, '\u535a\u58eb\u7814\u7a76\u751f')], default=0, verbose_name='\u5b66\u5386')),
                ('career', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u804c\u4e1a')),
                ('income', models.SmallIntegerField(choices=[(0, '\u672a\u900f\u9732'), (1, '0-5'), (2, '6-10'), (3, '11-15'), (4, '16-20'), (5, '20+')], default=0, verbose_name='\u5e74\u6536\u5165')),
                ('expect_marry_date', models.DateField(blank=True, null=True, verbose_name='\u671f\u671b\u7ed3\u5a5a\u65f6\u95f4')),
                ('nationality', models.CharField(blank=True, max_length=15, null=True, verbose_name='\u6c11\u65cf')),
                ('marriage_status', models.SmallIntegerField(choices=[(0, '\u672a\u900f\u9732'), (1, '\u672a\u5a5a'), (2, '\u5df2\u5a5a'), (3, '\u79bb\u5f02'), (4, '\u4e27\u5076')], default=0, verbose_name='\u5a5a\u59fb\u72b6\u51b5')),
                ('birth_index', models.IntegerField(blank=True, null=True, verbose_name='\u5bb6\u4e2d\u6392\u884c')),
                ('has_children', models.SmallIntegerField(choices=[(0, '\u672a\u900f\u9732'), (1, '\u65e0'), (2, '\u6709')], default=0, verbose_name='\u6709\u65e0\u5b50\u5973')),
                ('weight', models.IntegerField(blank=True, help_text='\u5355\u4f4d(KG)', null=True, verbose_name='\u4f53\u91cd')),
                ('avatar', models.URLField(blank=True, null=True, verbose_name='\u5934\u50cf')),
                ('vip_expire_date', models.DateField(blank=True, null=True, verbose_name='\u4f1a\u5458\u8fc7\u671f\u65e5\u671f')),
                ('identity_verified', models.BooleanField(default=False, verbose_name='\u8eab\u4efd\u8ba4\u8bc1')),
                ('has_car', models.BooleanField(default=False, verbose_name='\u662f\u5426\u8d2d\u8f66')),
                ('has_house', models.BooleanField(default=False, verbose_name='\u662f\u5426\u8d2d\u623f')),
                ('relationship_desc', models.TextField(blank=True, null=True, verbose_name='\u60c5\u611f\u7ecf\u5386')),
                ('mate_preference', models.TextField(blank=True, null=True, verbose_name='\u62e9\u5076\u6807\u51c6')),
                ('on_top', models.BooleanField(default=False, verbose_name='\u662f\u5426\u7f6e\u9876')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(max_length=20)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest', related_query_name='interest', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enjoy_love.PersonalTag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', related_query_name='tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '\u7528\u6237\u6807\u7b7e',
                'verbose_name_plural': '\u7528\u6237\u6807\u7b7e',
            },
        ),
        migrations.CreateModel(
            name='Vip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vip_type', models.CharField(max_length=20)),
                ('vip_month_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='\u5355\u6708\u4f1a\u5458\u4ef7')),
                ('vip_month_price_org', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='\u5355\u6708\u4f1a\u5458\u4ef7\u539f\u4ef7')),
                ('vip_half_year_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='\u534a\u5e74\u4f1a\u5458\u4ef7')),
                ('vip_half_year_price_org', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='\u534a\u5e74\u4f1a\u5458\u4ef7\u539f\u4ef7')),
                ('vip_year_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='\u4e00\u5e74\u4f1a\u5458\u4ef7')),
                ('vip_year_price_org', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='\u4e00\u5e74\u4f1a\u5458\u4ef7\u539f\u4ef7')),
                ('vip_member_count', models.IntegerField(blank=True, null=True, verbose_name='vip\u7528\u6237\u6570\u91cf')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '\u4f1a\u5458',
                'verbose_name_plural': '\u4f1a\u5458',
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='vip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enjoy_love.Vip'),
        ),
        migrations.AlterUniqueTogether(
            name='usertags',
            unique_together=set([('user', 'tag')]),
        ),
    ]
