# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enjoy_love', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='verify_code',
            field=models.IntegerField(blank=True, help_text='\u9a8c\u8bc1\u7801', null=True),
        ),
    ]
