# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 09:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='\u5e7f\u544a\u6761\u76ee')),
                ('desc', models.TextField(verbose_name='\u5e7f\u544a\u6587\u5b57')),
                ('img', models.TextField(verbose_name='\u56fe\u7247')),
                ('url', models.URLField(verbose_name='\u8df3\u8f6c\u5730\u5740')),
                ('valid', models.BooleanField(default=True, verbose_name='\u662f\u5426\u6709\u6548')),
                ('expire_time', models.DateTimeField(null=True, verbose_name='\u8fc7\u671f\u65f6\u95f4')),
                ('show_place', models.SmallIntegerField(choices=[(0, '\u6240\u6709\u4f4d\u7f6e'), (1, '\u4eba\u7269\u5217\u8868\u9875'), (2, '\u6587\u7ae0\u5217\u8868\u9875')], verbose_name='\u5c55\u793a\u7684tab')),
                ('show_page', models.IntegerField(default=1, verbose_name='\u5c55\u793a\u7684\u9875\u6570')),
                ('show_position', models.IntegerField(default=10, verbose_name='\u5c55\u793a\u7684\u4f4d\u7f6e')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '\u5e7f\u544a\u8bbe\u7f6e',
                'verbose_name_plural': '\u5e7f\u544a\u8bbe\u7f6e',
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_url', models.TextField(verbose_name='\u56fe\u7247\u5730\u5740')),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5220\u9664')),
                ('delete_time', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', related_query_name='albums', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '\u76f8\u518c',
                'verbose_name_plural': '\u76f8\u518c',
            },
        ),
        migrations.CreateModel(
            name='ContactExchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_status', models.SmallIntegerField(choices=[(0, '\u5f85\u5904\u7406'), (1, '\u540c\u610f'), (2, '\u62d2\u7edd')], default=0, verbose_name='\u72b6\u6001')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('exchange_receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_receiver', related_query_name='exchange_receiver', to=settings.AUTH_USER_MODEL)),
                ('exchange_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_sender', related_query_name='exchange_sender', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '\u8054\u7cfb\u65b9\u5f0f\u4ea4\u6362\u8bb0\u5f55',
                'verbose_name_plural': '\u8054\u7cfb\u65b9\u5f0f\u4ea4\u6362\u8bb0\u5f55',
            },
        ),
        migrations.CreateModel(
            name='ContactType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='\u4fe1\u606f\u7c7b\u578b')),
                ('valid', models.BooleanField(default=True, verbose_name='\u662f\u5426\u6709\u6548')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '\u8054\u7cfb\u65b9\u5f0f',
                'verbose_name_plural': '\u8054\u7cfb\u65b9\u5f0f',
            },
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(max_length=255, verbose_name='\u53cd\u9988\u5185\u5bb9')),
                ('photo_1', models.TextField(verbose_name='\u53cd\u9988\u56fe\u7247')),
                ('photo_2', models.TextField(verbose_name='\u53cd\u9988\u56fe\u72472')),
                ('status', models.SmallIntegerField(choices=[(0, '\u5f85\u5904\u7406'), (1, '\u5df2\u5904\u7406')], default=0, verbose_name='\u72b6\u6001')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '\u7528\u6237\u53cd\u9988',
                'verbose_name_plural': '\u7528\u6237\u53cd\u9988',
            },
        ),
        migrations.CreateModel(
            name='FilterControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u7b5b\u9009\u6761\u4ef6')),
                ('param', models.CharField(max_length=20, verbose_name='\u7b5b\u9009\u53c2\u6570')),
                ('valid', models.BooleanField(default=True, verbose_name='\u662f\u5426\u6709\u6548')),
            ],
            options={
                'verbose_name': '\u9996\u9875\u7b5b\u9009\u6761\u4ef6',
                'verbose_name_plural': '\u9996\u9875\u7b5b\u9009\u6761\u4ef6',
            },
        ),
        migrations.CreateModel(
            name='FilterOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_name', models.CharField(max_length=20, verbose_name='\u9009\u9879\u540d\u79f0')),
                ('option_value', models.CharField(max_length=20, verbose_name='\u9009\u9879\u503c')),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filter_options', related_query_name='filter_options', to='enjoy_love.FilterControl')),
            ],
            options={
                'verbose_name': '\u7b5b\u9009\u9009\u9879',
                'verbose_name_plural': '\u7b5b\u9009\u9009\u9879',
            },
        ),
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20, verbose_name='\u540d\u79f0')),
                ('value', models.CharField(max_length=100, verbose_name='\u503c')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='\u63cf\u8ff0')),
                ('valid', models.BooleanField(default=True, verbose_name='\u662f\u5426\u6709\u6548')),
            ],
            options={
                'verbose_name': 'app\u8bbe\u7f6e',
                'verbose_name_plural': 'app\u8bbe\u7f6e',
            },
        ),
        migrations.CreateModel(
            name='IdentityVerify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_name', models.CharField(max_length=20, verbose_name='\u771f\u5b9e\u59d3\u540d')),
                ('id_number', models.CharField(max_length=20, verbose_name='\u8eab\u4efd\u8bc1\u53f7')),
                ('img_front', models.URLField(verbose_name='\u6b63\u9762\u8eab\u4efd\u8bc1')),
                ('img_back', models.URLField(verbose_name='\u80cc\u9762\u8eab\u4efd\u8bc1')),
                ('status', models.SmallIntegerField(choices=[(0, '\u5f85\u5ba1\u6838'), (1, '\u5df2\u540c\u610f'), (2, '\u5df2\u62d2\u7edd')], default=0, verbose_name='\u5ba1\u6838\u72b6\u6001')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity', related_query_name='identity', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '\u8eab\u4efd\u8ba4\u8bc1',
                'verbose_name_plural': '\u8eab\u4efd\u8ba4\u8bc1',
            },
        ),
        migrations.CreateModel(
            name='LikeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('like_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likerecord', related_query_name='likerecord', to=settings.AUTH_USER_MODEL)),
                ('like_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liketorecord', related_query_name='liketorecord', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '\u5fc3\u52a8\u8bb0\u5f55',
                'verbose_name_plural': '\u5fc3\u52a8\u8bb0\u5f55',
            },
        ),
        migrations.CreateModel(
            name='PersonalInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u5174\u8da3\u7231\u597d')),
                ('valid', models.BooleanField(default=True, verbose_name='\u662f\u5426\u6709\u6548')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '\u5174\u8da3\u7231\u597d\u8bbe\u7f6e',
                'verbose_name_plural': '\u5174\u8da3\u7231\u597d\u8bbe\u7f6e',
            },
        ),
        migrations.CreateModel(
            name='PersonalTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u4e2a\u4eba\u6807\u7b7e')),
                ('valid', models.BooleanField(default=True, verbose_name='\u662f\u5426\u6709\u6548')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '\u4e2a\u4eba\u6807\u7b7e',
                'verbose_name_plural': '\u4e2a\u4eba\u6807\u7b7e',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='\u7528\u6237\u540d')),
                ('sex', models.SmallIntegerField(choices=[(0, '\u4e0d\u8be6'), (1, '\u7537'), (2, '\u5973')], default=0, verbose_name='\u6027\u522b')),
                ('person_intro', models.TextField(blank=True, max_length=1000, null=True, verbose_name='\u4e2a\u4eba\u7b80\u4ecb')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='\u51fa\u751f\u65e5\u671f')),
                ('work_area_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u5de5\u4f5c\u5730\u540d\u79f0')),
                ('work_area_code', models.CharField(blank=True, max_length=15, null=True, verbose_name='\u5de5\u4f5c\u5730\u7f16\u7801')),
                ('born_area_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u7c4d\u8d2f\u540d\u79f0')),
                ('born_area_code', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u7c4d\u8d2f\u7f16\u7801')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='\u8eab\u9ad8')),
                ('education', models.SmallIntegerField(choices=[(0, '\u672a\u900f\u9732'), (1, '\u9ad8\u4e2d'), (2, '\u5927\u4e13'), (3, '\u672c\u79d1'), (4, '\u7855\u58eb\u7814\u7a76\u751f'), (5, '\u535a\u58eb\u7814\u7a76\u751f')], default=0, verbose_name='\u5b66\u5386')),
                ('career', models.SmallIntegerField(choices=[(0, '\u672a\u900f\u9732'), (1, '\u5728\u6821\u5b66\u751f'), (2, '\u79c1\u8425\u4e1a\u4e3b'), (3, '\u519c\u4e1a\u52b3\u52a8\u8005'), (4, '\u4f01\u4e1a\u804c\u5de5'), (5, '\u653f\u5e9c\u673a\u5173/\u4e8b\u4e1a\u5355\u4f4d'), (6, '\u81ea\u7531\u804c\u4e1a')], default=0, verbose_name='\u804c\u4e1a')),
                ('income', models.SmallIntegerField(choices=[(0, '\u672a\u900f\u9732'), (1, '3k\u4ee5\u4e0b'), (2, '3k-5k'), (3, '58k'), (4, '8k-12k'), (5, '12k-20k'), (6, '20k-30k'), (7, '30k\u4ee5\u4e0a')], default=0, verbose_name='\u6708\u6536\u5165')),
                ('expect_marry_date', models.SmallIntegerField(choices=[(0, '\u672a\u900f\u9732'), (1, '\u534a\u5e74\u5185'), (2, '\u4e00\u5e74\u5185')], default=0, verbose_name='\u671f\u671b\u7ed3\u5a5a\u65f6\u95f4')),
                ('nationality', models.CharField(blank=True, max_length=15, null=True, verbose_name='\u6c11\u65cf')),
                ('marriage_status', models.SmallIntegerField(choices=[(0, '\u672a\u900f\u9732'), (1, '\u672a\u5a5a'), (2, '\u79bb\u5f02'), (3, '\u4e27\u5076')], default=0, verbose_name='\u5a5a\u59fb\u72b6\u51b5')),
                ('birth_index', models.IntegerField(blank=True, null=True, verbose_name='\u5bb6\u4e2d\u6392\u884c')),
                ('has_children', models.SmallIntegerField(choices=[(0, '\u672a\u900f\u9732'), (1, '\u65e0'), (2, '\u6709')], default=0, verbose_name='\u6709\u65e0\u5b50\u5973')),
                ('weight', models.IntegerField(blank=True, help_text='\u5355\u4f4d(KG)', null=True, verbose_name='\u4f53\u91cd')),
                ('avatar', models.URLField(blank=True, null=True, verbose_name='\u5934\u50cf')),
                ('vip_expire_date', models.DateField(blank=True, null=True, verbose_name='\u4f1a\u5458\u8fc7\u671f\u65e5\u671f')),
                ('identity_verified', models.BooleanField(default=False, verbose_name='\u8eab\u4efd\u8ba4\u8bc1')),
                ('has_car', models.SmallIntegerField(choices=[(0, '\u672a\u900f\u9732'), (1, '\u65e0'), (2, '\u6709')], default=0, verbose_name='\u662f\u5426\u8d2d\u8f66')),
                ('has_house', models.SmallIntegerField(choices=[(0, '\u672a\u900f\u9732'), (1, '\u65e0'), (2, '\u6709')], default=0, verbose_name='\u662f\u5426\u8d2d\u623f')),
                ('relationship_desc', models.TextField(blank=True, null=True, verbose_name='\u60c5\u611f\u7ecf\u5386')),
                ('mate_preference', models.TextField(blank=True, null=True, verbose_name='\u62e9\u5076\u6807\u51c6')),
                ('constellation', models.SmallIntegerField(choices=[(0, '\u672a\u900f\u9732'), (1, '\u767d\u7f8a\u5ea7'), (2, '\u91d1\u725b\u5ea7'), (3, '\u53cc\u5b50\u5ea7'), (4, '\u5de8\u87f9\u5ea7'), (5, '\u72ee\u5b50\u5ea7'), (6, '\u5904\u5973\u5ea7'), (7, '\u5929\u79e4\u5ea7'), (8, '\u5929\u874e\u5ea7'), (9, '\u5c04\u624b\u5ea7'), (10, '\u6469\u7faf\u5ea7'), (11, '\u6c34\u74f6\u5ea7'), (12, '\u53cc\u9c7c\u5ea7')], default=0, verbose_name='\u661f\u5ea7')),
                ('on_top', models.BooleanField(default=False, verbose_name='\u662f\u5426\u7f6e\u9876')),
                ('age', models.IntegerField(blank=True, default=0, verbose_name='\u5e74\u9f84')),
                ('like', models.IntegerField(default=0, verbose_name='\u5fc3\u52a8\u4eba\u6570')),
                ('can_post', models.BooleanField(default=True, verbose_name='\u80fd\u5426\u53d1\u5e16\u5b50')),
                ('platform', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u624b\u673a\u5e73\u53f0')),
                ('version_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u7248\u672c\u53f7')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=20, verbose_name='\u8054\u7cfb\u65b9\u5f0f\u5185\u5bb9')),
                ('deleted', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5220\u9664')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', related_query_name='contacts', to='enjoy_love.ContactType', verbose_name='\u8054\u7cfb\u65b9\u5f0f')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', related_query_name='contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '\u4e2a\u4eba\u901a\u8baf\u4fe1\u606f',
                'verbose_name_plural': '\u4e2a\u4eba\u901a\u8baf\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='UserInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest', related_query_name='interest', to='enjoy_love.PersonalInterest', verbose_name='\u5174\u8da3')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest', related_query_name='interest', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '\u5174\u8da3\u7231\u597d',
                'verbose_name_plural': '\u5174\u8da3\u7231\u597d',
            },
        ),
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='\u7559\u8a00\u5185\u5bb9')),
                ('deleted', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5220\u9664')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('message_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_from', related_query_name='messages_from', to=settings.AUTH_USER_MODEL)),
                ('message_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_to', related_query_name='messages_to', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '\u7559\u8a00',
                'verbose_name_plural': '\u7559\u8a00',
            },
        ),
        migrations.CreateModel(
            name='UserTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', related_query_name='tags', to='enjoy_love.PersonalTag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', related_query_name='tags', to=settings.AUTH_USER_MODEL, verbose_name='\u6807\u7b7e')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u6807\u7b7e',
                'verbose_name_plural': '\u7528\u6237\u6807\u7b7e',
            },
        ),
        migrations.CreateModel(
            name='Vip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vip_type', models.CharField(max_length=20)),
                ('vip_month_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='\u5355\u6708\u4f1a\u5458\u4ef7')),
                ('vip_month_price_org', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='\u5355\u6708\u4f1a\u5458\u4ef7\u539f\u4ef7')),
                ('vip_half_year_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='\u534a\u5e74\u4f1a\u5458\u4ef7')),
                ('vip_half_year_price_org', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='\u534a\u5e74\u4f1a\u5458\u4ef7\u539f\u4ef7')),
                ('vip_year_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='\u4e00\u5e74\u4f1a\u5458\u4ef7')),
                ('vip_year_price_org', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='\u4e00\u5e74\u4f1a\u5458\u4ef7\u539f\u4ef7')),
                ('vip_member_count', models.IntegerField(blank=True, null=True, verbose_name='vip\u7528\u6237\u6570\u91cf')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '\u4f1a\u5458',
                'verbose_name_plural': '\u4f1a\u5458',
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='vip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enjoy_love.Vip'),
        ),
        migrations.AddField(
            model_name='contactexchange',
            name='exchange_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_type', related_query_name='exchange_type', to='enjoy_love.ContactType'),
        ),
        migrations.AlterUniqueTogether(
            name='usertags',
            unique_together=set([('user', 'tag')]),
        ),
        migrations.AlterUniqueTogether(
            name='userinterest',
            unique_together=set([('user', 'interest')]),
        ),
        migrations.AlterUniqueTogether(
            name='usercontact',
            unique_together=set([('user', 'type')]),
        ),
        migrations.AlterUniqueTogether(
            name='likerecord',
            unique_together=set([('like_from', 'like_to')]),
        ),
    ]
